services:
  crm-wealify:
    image: crm_wealify/crm-wealify:dev-latest
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
    ports:
      - "8080:80"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - logistic-net

networks:
  logistic-net:
    external: true
